# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pM6cXWzoOZBjXG2vpOrTEoF1ouPloQoO
"""

print("olá, mundo!"
)

print("Agora saberei todos os segredos Python"
)