# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OYFmG4wH4dvsXl0R7MGE0hmoY1wguoGC
"""

print ("Poesia")
print ("De tudo, ao meu amor serei atento")
print ("Antes, e com tal zelo, e sempre, e tanto")
print ("Que mesmo em face do maior encanto")
print ("Dele se encante mais meu pensamento.")